<?xml version="1.0" encoding="UTF-8"?><testsuite failures="2" name="cucumber.runtime.formatter.JUnitFormatter" skipped="1" tests="4" time="0.141294">
<testcase classname="Testing" name="validate login Page" time="0.140126">
<system-out><![CDATA[Given Open login Page.......................................................passed
And Enter valid username and password.......................................passed
When clicked on login button................................................passed
Then should open Homepage...................................................passed
]]></system-out>
</testcase>
<testcase classname="API Testing" name="check flipkart Homepage api" time="0.000858">
<failure message="java.lang.AssertionError: expected [true] but found [false]&#13;&#10;&#9;at org.testng.Assert.fail(Assert.java:96)&#13;&#10;&#9;at org.testng.Assert.failNotEquals(Assert.java:776)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:44)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:54)&#13;&#10;&#9;at Globaltest.StepDefinitions.should_get_valid_HTTP_respone(StepDefinitions.java:47)&#13;&#10;&#9;at ✽.Then should get valid HTTP respone(Test2.feature:8)&#13;&#10;"><![CDATA[Given Set API endpoint......................................................passed
When run GET request........................................................passed
Then should get valid HTTP respone..........................................failed

StackTrace:
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at Globaltest.StepDefinitions.should_get_valid_HTTP_respone(StepDefinitions.java:47)
	at ✽.Then should get valid HTTP respone(Test2.feature:8)
]]></failure>
</testcase>
<testcase classname="validate Amazon" name="to validate login page of Amazon" time="0.000243">
<failure message="java.lang.AssertionError: expected [true] but found [false]&#13;&#10;&#9;at org.testng.Assert.fail(Assert.java:96)&#13;&#10;&#9;at org.testng.Assert.failNotEquals(Assert.java:776)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:44)&#13;&#10;&#9;at org.testng.Assert.assertTrue(Assert.java:54)&#13;&#10;&#9;at Globaltest.StepDefinitions.should_open_HomePage(StepDefinitions.java:69)&#13;&#10;&#9;at ✽.Then should open HomePage(valid_Amazon.feature:6)&#13;&#10;"><![CDATA[Given open login page.......................................................passed
And enter username and password.............................................passed
When click on login.........................................................passed
Then should open HomePage...................................................failed

StackTrace:
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:96)
	at org.testng.Assert.failNotEquals(Assert.java:776)
	at org.testng.Assert.assertTrue(Assert.java:44)
	at org.testng.Assert.assertTrue(Assert.java:54)
	at Globaltest.StepDefinitions.should_open_HomePage(StepDefinitions.java:69)
	at ✽.Then should open HomePage(valid_Amazon.feature:6)
]]></failure>
</testcase>
<testcase classname="validate UST" name="to validate login page of UST" time="0.000067">
<skipped><![CDATA[Given open login page.......................................................passed
And enter username and password.............................................passed
When click on login.........................................................passed
Then should open HomePage of UST............................................undefined
]]></skipped>
</testcase>
</testsuite>
